name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the workflow on push to the `main` branch (adjust as necessary)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust based on your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Assumes your project has a `build` script in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this secret
          publish_dir: ./build # The folder containing the built project (for create-react-app, Vite)

      - name: Clean up
        run: rm -rf ./build # Optional: Cleans up build directory after deployment
